name: DEV - Build

on:
  workflow_dispatch:
  
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  APP_NAME: [name]-tutorial-frontend
  CONTAINER_REPOSITORY: "acr[name]tutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

jobs:
  unitest:
    name: UnitTest
    runs-on: ubuntu-latest
    environment: env
    steps:
- name: Checkout code
  uses: actions/checkout@v2